### ISSUE TITLE
Mod with multiple options for different items

### ISSUE THREAD

**Issue by Dllsearch** [teutinsa/Helldivers2ModManager#2]
Mods with folders for different in game items (such weapons) but without manifests can't be used simultaneously.
Example: [EFT MDRs - Liberator Series Conversion](https://www.nexusmods.com/helldivers2/mods/730)
Mod have different liberator variations, yet I can choose only one variant for model replacement.
Can we have a checkbox for multiple variations, please?

**Comment by teutinsa** [comment]
A solution will be shipped in the coming update.
