### ISSUE TITLE
Question about Automatic Sorting in Helldivers 2 Mod Manager

### ISSUE THREAD

**Issue by GaricBear** [teutinsa/Helldivers2ModManager#4]
Hello,
I’ve been using the Helldivers 2 Mod Manager and really enjoy it. In the beta version, mods were forcibly sorted automatically, but it seems like automatic sorting is not supported in the official version. Is there a way to enable automatic sorting in the current version?

Thank you!

**Comment by teutinsa** [comment]
I the beta there was no load order. Now there is, which means that the order of your mods in the manager list matters now. The sorting of the beta was merely an artifact of the list automatically sorting its content alphabetically.
